package com.cyber.wom;

import com.cyber.wom.block.ModBlocks;
import com.cyber.wom.item.ModItems;
import net.minecraft.world.item.CreativeModeTabs;
import org.slf4j.Logger;

import com.mojang.logging.LogUtils;

import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.Mod;
import net.neoforged.fml.config.ModConfig;
import net.neoforged.fml.ModContainer;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraft.client.Minecraft;
import net.neoforged.fml.event.lifecycle.FMLCommonSetupEvent;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.event.BuildCreativeModeTabContentsEvent;
import net.neoforged.neoforge.event.server.ServerStartingEvent;

@Mod(WOM.MOD_ID)
public class WOM {
    public static final String MOD_ID = "worldofmetal";
    public static final Logger LOGGER = LogUtils.getLogger();

    // The constructor for the mod class is the first code that is run when your mod is loaded.
    // FML will recognize some parameter types like IEventBus or ModContainer and pass them in automatically.
    public WOM(IEventBus modEventBus, ModContainer modContainer) {
        // Register the commonSetup method for modloading
        modEventBus.addListener(this::commonSetup);

        NeoForge.EVENT_BUS.register(this);

        ModItems.register(modEventBus);
        ModBlocks.register(modEventBus);

        modEventBus.addListener(this::addCreative);

        modContainer.registerConfig(ModConfig.Type.COMMON, Config.SPEC);
    }

    private void commonSetup(FMLCommonSetupEvent event) {

    }

    // Add the example block item to the building blocks tab
    private void addCreative(BuildCreativeModeTabContentsEvent event) {
        if (event.getTabKey() == CreativeModeTabs.INGREDIENTS) {
            event.accept(ModItems.ALUMINUM);
            event.accept(ModItems.ZINC);
            event.accept(ModItems.NICKEL);
            event.accept(ModItems.TIN);
            event.accept(ModItems.LEAD);
            event.accept(ModItems.CHROMIUM);
            event.accept(ModItems.MANGANESE);
            event.accept(ModItems.COBALT);
            event.accept(ModItems.MAGNESIUM);
            event.accept(ModItems.TITANIUM);
            event.accept(ModItems.VANADIUM);
            event.accept(ModItems.BISMUTH);
            event.accept(ModItems.ANTIMONY);
            event.accept(ModItems.LITHIUM);
            event.accept(ModItems.SODIUM);
            event.accept(ModItems.MOLYBDENUM);
            event.accept(ModItems.SILVER);
            event.accept(ModItems.PLATINUM);
            event.accept(ModItems.PALLADIUM);
            event.accept(ModItems.RHODIUM);
            event.accept(ModItems.IRIDIUM);
            event.accept(ModItems.OSMIUM);
            event.accept(ModItems.RUTHENIUM);
            event.accept(ModItems.TANTALUM);
            event.accept(ModItems.NIOBIUM);
            event.accept(ModItems.HAFNIUM);
            event.accept(ModItems.ZIRCONIUM);
            event.accept(ModItems.RHENIUM);
            event.accept(ModItems.TECHNETIUM);
            event.accept(ModItems.PROTACTINIUM);
            event.accept(ModItems.NEPTUNIUM);
            event.accept(ModItems.AMERICIUM);
            event.accept(ModItems.CURIUM);
            event.accept(ModItems.BERKELIUM);
            event.accept(ModItems.CALIFORNIUM);
            event.accept(ModItems.EINSTEINIUM);
            event.accept(ModItems.FERMIUM);
            event.accept(ModItems.MENDELEVIUM);
            event.accept(ModItems.NOBELIUM);
            event.accept(ModItems.LAWRENCIUM);
            event.accept(ModItems.RUTHERFORDIUM);
            event.accept(ModItems.DUBNIUM);
            event.accept(ModItems.SEABORGIUM);
            event.accept(ModItems.BOHRIUM);
            event.accept(ModItems.HASSIUM);
            event.accept(ModItems.MEITNERIUM);
            event.accept(ModItems.DARMSTADTIUM);
            event.accept(ModItems.ROENTGENIUM);
            event.accept(ModItems.COPERNICIUM);
            event.accept(ModItems.NIHONIUM);
            event.accept(ModItems.FLEROVIUM);
            event.accept(ModItems.MOSCOVIUM);
            event.accept(ModItems.LIVERMORIUM);
            event.accept(ModItems.TENNESSINE);
            event.accept(ModItems.OGANESSON);
            event.accept(ModItems.FRANCIUM);
            event.accept(ModItems.RADIUM);
            event.accept(ModItems.POLONIUM);
            event.accept(ModItems.CITRINE);
            event.accept(ModItems.SMOKY_QUARTZ);
            event.accept(ModItems.AGATE);
            event.accept(ModItems.JASPER);
            event.accept(ModItems.ONYX);
            event.accept(ModItems.CALCITE);
            event.accept(ModItems.FLUORITE);
            event.accept(ModItems.OBSIDIAN);
            event.accept(ModItems.AVENTURINE);
            event.accept(ModItems.TIGERS_EYE);
            event.accept(ModItems.SODALITE);
            event.accept(ModItems.APATITE);
            event.accept(ModItems.MALACHITE);
            event.accept(ModItems.CHALCEDONY);
            event.accept(ModItems.LABRADORITE);
            event.accept(ModItems.CARNELIAN);
            event.accept(ModItems.MOONSTONE);
            event.accept(ModItems.HOWLITE);
            event.accept(ModItems.TURQUOISE);
            event.accept(ModItems.PERIDOT);
            event.accept(ModItems.TOPAZ);
            event.accept(ModItems.GARNET);
            event.accept(ModItems.ZIRCON);
            event.accept(ModItems.SPINEL);
            event.accept(ModItems.KYANITE);
            event.accept(ModItems.AMAZONITE);
            event.accept(ModItems.SUNSTONE);
            event.accept(ModItems.RHODONITE);
            event.accept(ModItems.PREHNITE);
            event.accept(ModItems.IOLITE);
            event.accept(ModItems.CHRYSOPRASE);
            event.accept(ModItems.AVENTURINE_FELDSPAR);
            event.accept(ModItems.JADE_NEFRITE);
            event.accept(ModItems.JADE_JADEITE);
            event.accept(ModItems.RUTILE);
            event.accept(ModItems.DIOPSIDE);
            event.accept(ModItems.LEPIDOLITE);
            event.accept(ModItems.CHAROITE);
            event.accept(ModItems.ZOISITE_TANZANITE);
            event.accept(ModItems.SPINEL_RARE);
            event.accept(ModItems.KUNZITE);
            event.accept(ModItems.SPHENE);
            event.accept(ModItems.CHRYSOBERYL);
            event.accept(ModItems.HESSONITE);
            event.accept(ModItems.GROSSULAR);
            event.accept(ModItems.PYROPE);
            event.accept(ModItems.ALMANDINE);
            event.accept(ModItems.RHODOLITE);
            event.accept(ModItems.TORMALINE);
            event.accept(ModItems.SAPPHIRE);
            event.accept(ModItems.RUBY);
            event.accept(ModItems.OPAL);
            event.accept(ModItems.SPINEL_BLUE);
            event.accept(ModItems.AQUAMARINE);
            event.accept(ModItems.CHRYSOBERYL_CATSEYE);
            event.accept(ModItems.APATITE_RARE);
            event.accept(ModItems.BENITOITE);
            event.accept(ModItems.EUCLASE);
            event.accept(ModItems.KEMPTONITE);
            event.accept(ModItems.DANBURITE);
            event.accept(ModItems.SUGILITE);
            event.accept(ModItems.CHRYSOPRASE_RARE);
            event.accept(ModItems.AMETRINE);
            event.accept(ModItems.TORMALINE_RARE);
            event.accept(ModItems.SPINEL_RED);
            event.accept(ModItems.TOURMALINE_PINK);
            event.accept(ModItems.SPINEL_PURPLE);
            event.accept(ModItems.IOLITE_RARE);
            event.accept(ModItems.ANDALUSITE);
            event.accept(ModItems.DIASPORE);
            event.accept(ModItems.TUNSTALLITE);
            event.accept(ModItems.SAPPHIRE_PINK);
            event.accept(ModItems.SPINEL_GREEN);
            event.accept(ModItems.CHRYSOBERYL_ALMANDINE);
            event.accept(ModItems.PAINITE);
            event.accept(ModItems.TAAFFEITE);
            event.accept(ModItems.MUSGRAVITE);
            event.accept(ModItems.ALEXANDRITE);
            event.accept(ModItems.RED_BERIL);
            event.accept(ModItems.JEREMEJEVITE);
            event.accept(ModItems.GRANDIDIERITE);
            event.accept(ModItems.POUDRETTEITE);
            event.accept(ModItems.SERENDIBITE);
            event.accept(ModItems.BURMESE_RUBY);
            event.accept(ModItems.BLUE_DIAMOND);
            event.accept(ModItems.RED_DIAMOND);
            event.accept(ModItems.PINK_STAR_DIAMOND);
        }
        if (event.getTabKey() == CreativeModeTabs.BUILDING_BLOCKS) {
            event.accept(ModBlocks.PERIDOT_BLOCK);
            event.accept(ModBlocks.TIN_BLOCK);
            event.accept(ModBlocks.MANGANESE_BLOCK);
            event.accept(ModBlocks.TANTALUM_BLOCK);
            event.accept(ModBlocks.FRANCIUM_BLOCK);
            event.accept(ModBlocks.AMAZONITE_BLOCK);
            event.accept(ModBlocks.EUCLASE_BLOCK);
            event.accept(ModBlocks.JADE_JADEITE_BLOCK);
            event.accept(ModBlocks.TOURMALINE_PINK_BLOCK);
            event.accept(ModBlocks.JASPER_BLOCK);
            event.accept(ModBlocks.SUGILITE_BLOCK);
            event.accept(ModBlocks.NIHONIUM_BLOCK);
            event.accept(ModBlocks.VANADIUM_BLOCK);
            event.accept(ModBlocks.PLATINUM_BLOCK);
            event.accept(ModBlocks.ONYX_BLOCK);
            event.accept(ModBlocks.ANDALUSITE_BLOCK);
            event.accept(ModBlocks.RED_BERIL_BLOCK);
            event.accept(ModBlocks.ZINC_BLOCK);
            event.accept(ModBlocks.BOHRIUM_BLOCK);
            event.accept(ModBlocks.MEITNERIUM_BLOCK);
            event.accept(ModBlocks.SODALITE_BLOCK);
            event.accept(ModBlocks.LEAD_BLOCK);
            event.accept(ModBlocks.TIGERS_EYE_BLOCK);
            event.accept(ModBlocks.ANTIMONY_BLOCK);
            event.accept(ModBlocks.TITANIUM_BLOCK);
            event.accept(ModBlocks.SAPPHIRE_BLOCK);
            event.accept(ModBlocks.RED_DIAMOND_BLOCK);
            event.accept(ModBlocks.BERKELIUM_BLOCK);
            event.accept(ModBlocks.SPHENE_BLOCK);
            event.accept(ModBlocks.MAGNESIUM_BLOCK);
            event.accept(ModBlocks.FLUORITE_BLOCK);
            event.accept(ModBlocks.RUTILE_BLOCK);
            event.accept(ModBlocks.PROTACTINIUM_BLOCK);
            event.accept(ModBlocks.BENITOITE_BLOCK);
            event.accept(ModBlocks.ZIRCONIUM_BLOCK);
            event.accept(ModBlocks.TAAFFEITE_BLOCK);
            event.accept(ModBlocks.IOLITE_BLOCK);
            event.accept(ModBlocks.ALUMINUM_BLOCK);
            event.accept(ModBlocks.SEABORGIUM_BLOCK);
            event.accept(ModBlocks.DIOPSIDE_BLOCK);
            event.accept(ModBlocks.MENDELEVIUM_BLOCK);
            event.accept(ModBlocks.SODIUM_BLOCK);
            event.accept(ModBlocks.LEPIDOLITE_BLOCK);
            event.accept(ModBlocks.OPAL_BLOCK);
            event.accept(ModBlocks.POLONIUM_BLOCK);
            event.accept(ModBlocks.RUBY_BLOCK);
            event.accept(ModBlocks.EINSTEINIUM_BLOCK);
            event.accept(ModBlocks.PAINITE_BLOCK);
            event.accept(ModBlocks.IRIDIUM_BLOCK);
            event.accept(ModBlocks.SPINEL_GREEN_BLOCK);
            event.accept(ModBlocks.TENNESSINE_BLOCK);
            event.accept(ModBlocks.RUTHERFORDIUM_BLOCK);
            event.accept(ModBlocks.HAFNIUM_BLOCK);
            event.accept(ModBlocks.COPERNICIUM_BLOCK);
            event.accept(ModBlocks.ZOISITE_TANZANITE_BLOCK);
            event.accept(ModBlocks.JEREMEJEVITE_BLOCK);
            event.accept(ModBlocks.MOLYBDENUM_BLOCK);
            event.accept(ModBlocks.RHODOLITE_BLOCK);
            event.accept(ModBlocks.FERMIUM_BLOCK);
            event.accept(ModBlocks.RADIUM_BLOCK);
            event.accept(ModBlocks.DANBURITE_BLOCK);
            event.accept(ModBlocks.GRANDIDIERITE_BLOCK);
            event.accept(ModBlocks.KYANITE_BLOCK);
            event.accept(ModBlocks.APATITE_BLOCK);
            event.accept(ModBlocks.CHAROITE_BLOCK);
            event.accept(ModBlocks.SERENDIBITE_BLOCK);
            event.accept(ModBlocks.TECHNETIUM_BLOCK);
            event.accept(ModBlocks.PREHNITE_BLOCK);
            event.accept(ModBlocks.HOWLITE_BLOCK);
            event.accept(ModBlocks.MALACHITE_BLOCK);
            event.accept(ModBlocks.AVENTURINE_FELDSPAR_BLOCK);
            event.accept(ModBlocks.PINK_STAR_DIAMOND_BLOCK);
            event.accept(ModBlocks.CHRYSOPRASE_BLOCK);
            event.accept(ModBlocks.COBALT_BLOCK);
            event.accept(ModBlocks.SAPPHIRE_PINK_BLOCK);
            event.accept(ModBlocks.MUSGRAVITE_BLOCK);
            event.accept(ModBlocks.GROSSULAR_BLOCK);
            event.accept(ModBlocks.CHRYSOBERYL_CATSEYE_BLOCK);
            event.accept(ModBlocks.CALCITE_BLOCK);
            event.accept(ModBlocks.APATITE_RARE_BLOCK);
            event.accept(ModBlocks.JADE_NEFRITE_BLOCK);
            event.accept(ModBlocks.DUBNIUM_BLOCK);
            event.accept(ModBlocks.CHRYSOBERYL_BLOCK);
            event.accept(ModBlocks.CARNELIAN_BLOCK);
            event.accept(ModBlocks.OSMIUM_BLOCK);
            event.accept(ModBlocks.SPINEL_RED_BLOCK);
            event.accept(ModBlocks.ALMANDINE_BLOCK);
            event.accept(ModBlocks.SPINEL_BLUE_BLOCK);
            event.accept(ModBlocks.BLUE_DIAMOND_BLOCK);
            event.accept(ModBlocks.ZIRCON_BLOCK);
            event.accept(ModBlocks.SPINEL_RARE_BLOCK);
            event.accept(ModBlocks.SPINEL_BLOCK);
            event.accept(ModBlocks.SUNSTONE_BLOCK);
            event.accept(ModBlocks.POUDRETTEITE_BLOCK);
            event.accept(ModBlocks.NOBELIUM_BLOCK);
            event.accept(ModBlocks.KEMPTONITE_BLOCK);
            event.accept(ModBlocks.IOLITE_RARE_BLOCK);
            event.accept(ModBlocks.LAWRENCIUM_BLOCK);
            event.accept(ModBlocks.AGATE_BLOCK);
            event.accept(ModBlocks.AQUAMARINE_BLOCK);
            event.accept(ModBlocks.CHRYSOBERYL_ALMANDINE_BLOCK);
            event.accept(ModBlocks.CALIFORNIUM_BLOCK);
            event.accept(ModBlocks.TORMALINE_RARE_BLOCK);
            event.accept(ModBlocks.FLEROVIUM_BLOCK);
            event.accept(ModBlocks.TURQUOISE_BLOCK);
            event.accept(ModBlocks.SILVER_BLOCK);
            event.accept(ModBlocks.RHODIUM_BLOCK);
            event.accept(ModBlocks.MOSCOVIUM_BLOCK);
            event.accept(ModBlocks.LITHIUM_BLOCK);
            event.accept(ModBlocks.OGANESSON_BLOCK);
            event.accept(ModBlocks.TUNSTALLITE_BLOCK);
            event.accept(ModBlocks.RUTHENIUM_BLOCK);
            event.accept(ModBlocks.DIASPORE_BLOCK);
            event.accept(ModBlocks.ROENTGENIUM_BLOCK);
            event.accept(ModBlocks.NIOBIUM_BLOCK);
            event.accept(ModBlocks.NICKEL_BLOCK);
            event.accept(ModBlocks.CHROMIUM_BLOCK);
            event.accept(ModBlocks.DARMSTADTIUM_BLOCK);
            event.accept(ModBlocks.BISMUTH_BLOCK);
            event.accept(ModBlocks.MOONSTONE_BLOCK);
            event.accept(ModBlocks.SMOKY_QUARTZ_BLOCK);
            event.accept(ModBlocks.KUNZITE_BLOCK);
            event.accept(ModBlocks.CHRYSOPRASE_RARE_BLOCK);
            event.accept(ModBlocks.CITRINE_BLOCK);
            event.accept(ModBlocks.TOPAZ_BLOCK);
            event.accept(ModBlocks.HESSONITE_BLOCK);
            event.accept(ModBlocks.TORMALINE_BLOCK);
            event.accept(ModBlocks.RHODONITE_BLOCK);
            event.accept(ModBlocks.AVENTURINE_BLOCK);
            event.accept(ModBlocks.PALLADIUM_BLOCK);
            event.accept(ModBlocks.LABRADORITE_BLOCK);
            event.accept(ModBlocks.PYROPE_BLOCK);
            event.accept(ModBlocks.CURIUM_BLOCK);
            event.accept(ModBlocks.SPINEL_PURPLE_BLOCK);
            event.accept(ModBlocks.HASSIUM_BLOCK);
            event.accept(ModBlocks.LIVERMORIUM_BLOCK);
            event.accept(ModBlocks.CHALCEDONY_BLOCK);
            event.accept(ModBlocks.RHENIUM_BLOCK);
            event.accept(ModBlocks.BURMESE_RUBY_BLOCK);
            event.accept(ModBlocks.AMETRINE_BLOCK);
            event.accept(ModBlocks.NEPTUNIUM_BLOCK);
            event.accept(ModBlocks.ALEXANDRITE_BLOCK);
            event.accept(ModBlocks.AMERICIUM_BLOCK);
            event.accept(ModBlocks.MAGNESIUM_ORE_BLOCK);
            event.accept(ModBlocks.PERIDOT_ORE_BLOCK);
            event.accept(ModBlocks.ANDALUSITE_ORE_BLOCK);
            event.accept(ModBlocks.JADE_NEFRITE_ORE_BLOCK);
            event.accept(ModBlocks.LIVERMORIUM_ORE_BLOCK);
            event.accept(ModBlocks.TAAFFEITE_ORE_BLOCK);
            event.accept(ModBlocks.DARMSTADTIUM_ORE_BLOCK);
            event.accept(ModBlocks.SPINEL_PURPLE_ORE_BLOCK);
            event.accept(ModBlocks.IOLITE_RARE_ORE_BLOCK);
            event.accept(ModBlocks.TUNSTALLITE_ORE_BLOCK);
            event.accept(ModBlocks.PYROPE_ORE_BLOCK);
            event.accept(ModBlocks.FRANCIUM_ORE_BLOCK);
            event.accept(ModBlocks.SILVER_ORE_BLOCK);
            event.accept(ModBlocks.KEMPTONITE_ORE_BLOCK);
            event.accept(ModBlocks.PAINITE_ORE_BLOCK);
            event.accept(ModBlocks.DIOPSIDE_ORE_BLOCK);
            event.accept(ModBlocks.ZIRCONIUM_ORE_BLOCK);
            event.accept(ModBlocks.JASPER_ORE_BLOCK);
            event.accept(ModBlocks.SEABORGIUM_ORE_BLOCK);
            event.accept(ModBlocks.ALMANDINE_ORE_BLOCK);
            event.accept(ModBlocks.OGANESSON_ORE_BLOCK);
            event.accept(ModBlocks.JADE_JADEITE_ORE_BLOCK);
            event.accept(ModBlocks.SAPPHIRE_ORE_BLOCK);
            event.accept(ModBlocks.TITANIUM_ORE_BLOCK);
            event.accept(ModBlocks.ZOISITE_TANZANITE_ORE_BLOCK);
            event.accept(ModBlocks.BENITOITE_ORE_BLOCK);
            event.accept(ModBlocks.SMOKY_QUARTZ_ORE_BLOCK);
            event.accept(ModBlocks.NICKEL_ORE_BLOCK);
            event.accept(ModBlocks.BISMUTH_ORE_BLOCK);
            event.accept(ModBlocks.HAFNIUM_ORE_BLOCK);
            event.accept(ModBlocks.RHODOLITE_ORE_BLOCK);
            event.accept(ModBlocks.CURIUM_ORE_BLOCK);
            event.accept(ModBlocks.IRIDIUM_ORE_BLOCK);
            event.accept(ModBlocks.NIOBIUM_ORE_BLOCK);
            event.accept(ModBlocks.IOLITE_ORE_BLOCK);
            event.accept(ModBlocks.CHRYSOBERYL_ORE_BLOCK);
            event.accept(ModBlocks.RUBY_ORE_BLOCK);
            event.accept(ModBlocks.AGATE_ORE_BLOCK);
            event.accept(ModBlocks.BLUE_DIAMOND_ORE_BLOCK);
            event.accept(ModBlocks.DANBURITE_ORE_BLOCK);
            event.accept(ModBlocks.AMERICIUM_ORE_BLOCK);
            event.accept(ModBlocks.GRANDIDIERITE_ORE_BLOCK);
            event.accept(ModBlocks.LAWRENCIUM_ORE_BLOCK);
            event.accept(ModBlocks.MANGANESE_ORE_BLOCK);
            event.accept(ModBlocks.TORMALINE_ORE_BLOCK);
            event.accept(ModBlocks.PALLADIUM_ORE_BLOCK);
            event.accept(ModBlocks.HESSONITE_ORE_BLOCK);
            event.accept(ModBlocks.ALUMINUM_ORE_BLOCK);
            event.accept(ModBlocks.DUBNIUM_ORE_BLOCK);
            event.accept(ModBlocks.LEAD_ORE_BLOCK);
            event.accept(ModBlocks.APATITE_ORE_BLOCK);
            event.accept(ModBlocks.SPHENE_ORE_BLOCK);
            event.accept(ModBlocks.MEITNERIUM_ORE_BLOCK);
            event.accept(ModBlocks.BERKELIUM_ORE_BLOCK);
            event.accept(ModBlocks.MALACHITE_ORE_BLOCK);
            event.accept(ModBlocks.CHAROITE_ORE_BLOCK);
            event.accept(ModBlocks.TECHNETIUM_ORE_BLOCK);
            event.accept(ModBlocks.JEREMEJEVITE_ORE_BLOCK);
            event.accept(ModBlocks.HOWLITE_ORE_BLOCK);
            event.accept(ModBlocks.SPINEL_RED_ORE_BLOCK);
            event.accept(ModBlocks.MOLYBDENUM_ORE_BLOCK);
            event.accept(ModBlocks.TIN_ORE_BLOCK);
            event.accept(ModBlocks.OPAL_ORE_BLOCK);
            event.accept(ModBlocks.FLUORITE_ORE_BLOCK);
            event.accept(ModBlocks.RADIUM_ORE_BLOCK);
            event.accept(ModBlocks.CITRINE_ORE_BLOCK);
            event.accept(ModBlocks.FLEROVIUM_ORE_BLOCK);
            event.accept(ModBlocks.PLATINUM_ORE_BLOCK);
            event.accept(ModBlocks.LITHIUM_ORE_BLOCK);
            event.accept(ModBlocks.EINSTEINIUM_ORE_BLOCK);
            event.accept(ModBlocks.PINK_STAR_DIAMOND_ORE_BLOCK);
            event.accept(ModBlocks.CALIFORNIUM_ORE_BLOCK);
            event.accept(ModBlocks.KUNZITE_ORE_BLOCK);
            event.accept(ModBlocks.CALCITE_ORE_BLOCK);
            event.accept(ModBlocks.ZINC_ORE_BLOCK);
            event.accept(ModBlocks.RUTHENIUM_ORE_BLOCK);
            event.accept(ModBlocks.PREHNITE_ORE_BLOCK);
            event.accept(ModBlocks.NOBELIUM_ORE_BLOCK);
            event.accept(ModBlocks.SUGILITE_ORE_BLOCK);
            event.accept(ModBlocks.RHODIUM_ORE_BLOCK);
            event.accept(ModBlocks.PROTACTINIUM_ORE_BLOCK);
            event.accept(ModBlocks.SUNSTONE_ORE_BLOCK);
            event.accept(ModBlocks.SODIUM_ORE_BLOCK);
            event.accept(ModBlocks.RED_BERIL_ORE_BLOCK);
            event.accept(ModBlocks.EUCLASE_ORE_BLOCK);
            event.accept(ModBlocks.FERMIUM_ORE_BLOCK);
            event.accept(ModBlocks.CHROMIUM_ORE_BLOCK);
            event.accept(ModBlocks.SERENDIBITE_ORE_BLOCK);
            event.accept(ModBlocks.SPINEL_ORE_BLOCK);
            event.accept(ModBlocks.NIHONIUM_ORE_BLOCK);
            event.accept(ModBlocks.CARNELIAN_ORE_BLOCK);
            event.accept(ModBlocks.ANTIMONY_ORE_BLOCK);
            event.accept(ModBlocks.BURMESE_RUBY_ORE_BLOCK);
            event.accept(ModBlocks.COPERNICIUM_ORE_BLOCK);
            event.accept(ModBlocks.TOURMALINE_PINK_ORE_BLOCK);
            event.accept(ModBlocks.DIASPORE_ORE_BLOCK);
            event.accept(ModBlocks.LEPIDOLITE_ORE_BLOCK);
            event.accept(ModBlocks.CHALCEDONY_ORE_BLOCK);
            event.accept(ModBlocks.SODALITE_ORE_BLOCK);
            event.accept(ModBlocks.SPINEL_RARE_ORE_BLOCK);
            event.accept(ModBlocks.KYANITE_ORE_BLOCK);
            event.accept(ModBlocks.TANTALUM_ORE_BLOCK);
            event.accept(ModBlocks.VANADIUM_ORE_BLOCK);
            event.accept(ModBlocks.HASSIUM_ORE_BLOCK);
            event.accept(ModBlocks.TOPAZ_ORE_BLOCK);
            event.accept(ModBlocks.AMETRINE_ORE_BLOCK);
            event.accept(ModBlocks.ALEXANDRITE_ORE_BLOCK);
            event.accept(ModBlocks.ZIRCON_ORE_BLOCK);
            event.accept(ModBlocks.MOONSTONE_ORE_BLOCK);
            event.accept(ModBlocks.NEPTUNIUM_ORE_BLOCK);
            event.accept(ModBlocks.MENDELEVIUM_ORE_BLOCK);
            event.accept(ModBlocks.SPINEL_GREEN_ORE_BLOCK);
            event.accept(ModBlocks.POLONIUM_ORE_BLOCK);
            event.accept(ModBlocks.SPINEL_BLUE_ORE_BLOCK);
            event.accept(ModBlocks.TIGERS_EYE_ORE_BLOCK);
            event.accept(ModBlocks.CHRYSOBERYL_ALMANDINE_ORE_BLOCK);
            event.accept(ModBlocks.BOHRIUM_ORE_BLOCK);
            event.accept(ModBlocks.LABRADORITE_ORE_BLOCK);
            event.accept(ModBlocks.AQUAMARINE_ORE_BLOCK);
            event.accept(ModBlocks.MUSGRAVITE_ORE_BLOCK);
            event.accept(ModBlocks.RHENIUM_ORE_BLOCK);
            event.accept(ModBlocks.TENNESSINE_ORE_BLOCK);
            event.accept(ModBlocks.AVENTURINE_ORE_BLOCK);
            event.accept(ModBlocks.CHRYSOPRASE_ORE_BLOCK);
            event.accept(ModBlocks.CHRYSOPRASE_RARE_ORE_BLOCK);
            event.accept(ModBlocks.AMAZONITE_ORE_BLOCK);
            event.accept(ModBlocks.ROENTGENIUM_ORE_BLOCK);
            event.accept(ModBlocks.OSMIUM_ORE_BLOCK);
            event.accept(ModBlocks.GROSSULAR_ORE_BLOCK);
            event.accept(ModBlocks.RED_DIAMOND_ORE_BLOCK);
            event.accept(ModBlocks.ONYX_ORE_BLOCK);
            event.accept(ModBlocks.APATITE_RARE_ORE_BLOCK);
            event.accept(ModBlocks.COBALT_ORE_BLOCK);
            event.accept(ModBlocks.TURQUOISE_ORE_BLOCK);
            event.accept(ModBlocks.AVENTURINE_FELDSPAR_ORE_BLOCK);
            event.accept(ModBlocks.MOSCOVIUM_ORE_BLOCK);
            event.accept(ModBlocks.SAPPHIRE_PINK_ORE_BLOCK);
            event.accept(ModBlocks.TORMALINE_RARE_ORE_BLOCK);
            event.accept(ModBlocks.CHRYSOBERYL_CATSEYE_ORE_BLOCK);
            event.accept(ModBlocks.RUTHERFORDIUM_ORE_BLOCK);
            event.accept(ModBlocks.RHODONITE_ORE_BLOCK);
            event.accept(ModBlocks.RUTILE_ORE_BLOCK);
            event.accept(ModBlocks.POUDRETTEITE_ORE_BLOCK);

        }
    }

    // You can use SubscribeEvent and let the Event Bus discover methods to call
    @SubscribeEvent
    public void onServerStarting(ServerStartingEvent event) {

    }

    // You can use EventBusSubscriber to automatically register all static methods in the class annotated with @SubscribeEvent
    @EventBusSubscriber(modid = WOM.MOD_ID, bus = EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
    static class ClientModEvents {
        @SubscribeEvent
        static void onClientSetup(FMLClientSetupEvent event) {
            // Some client setup code
            LOGGER.info("HELLO FROM CLIENT SETUP");
            LOGGER.info("MINECRAFT NAME >> {}", Minecraft.getInstance().getUser().getName());
        }
    }
}
