package com.cyber.wom.datagen;

import com.cyber.wom.block.ModBlocks;
import com.cyber.wom.item.ModItems;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.loot.BlockLootSubProvider;
import net.minecraft.world.flag.FeatureFlags;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraft.world.item.enchantment.Enchantments;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.storage.loot.LootTable;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.functions.ApplyBonusCount;
import net.minecraft.world.level.storage.loot.functions.SetItemCountFunction;
import net.minecraft.world.level.storage.loot.providers.number.UniformGenerator;

import java.util.Set;

public class ModBlockLootTableProvider extends BlockLootSubProvider {
    protected ModBlockLootTableProvider(HolderLookup.Provider registries) {
        super(Set.of(), FeatureFlags.REGISTRY.allFlags(), registries);
    }

    @Override
    protected void generate() {
        dropSelf(ModBlocks.PLATINUM_BLOCK.get());
        dropSelf(ModBlocks.DARMSTADTIUM_BLOCK.get());
        dropSelf(ModBlocks.LAWRENCIUM_BLOCK.get());
        dropSelf(ModBlocks.RUTHERFORDIUM_BLOCK.get());
        dropSelf(ModBlocks.MOLYBDENUM_BLOCK.get());
        dropSelf(ModBlocks.MANGANESE_BLOCK.get());
        dropSelf(ModBlocks.ZIRCON_BLOCK.get());
        dropSelf(ModBlocks.HASSIUM_BLOCK.get());
        dropSelf(ModBlocks.PINK_STAR_DIAMOND_BLOCK.get());
        dropSelf(ModBlocks.SPHENE_BLOCK.get());
        dropSelf(ModBlocks.CURIUM_BLOCK.get());
        dropSelf(ModBlocks.SPINEL_BLUE_BLOCK.get());
        dropSelf(ModBlocks.RHODOLITE_BLOCK.get());
        dropSelf(ModBlocks.POUDRETTEITE_BLOCK.get());
        dropSelf(ModBlocks.BENITOITE_BLOCK.get());
        dropSelf(ModBlocks.FERMIUM_BLOCK.get());
        dropSelf(ModBlocks.PERIDOT_BLOCK.get());
        dropSelf(ModBlocks.ZINC_BLOCK.get());
        dropSelf(ModBlocks.FLEROVIUM_BLOCK.get());
        dropSelf(ModBlocks.SPINEL_RARE_BLOCK.get());
        dropSelf(ModBlocks.BISMUTH_BLOCK.get());
        dropSelf(ModBlocks.IOLITE_BLOCK.get());
        dropSelf(ModBlocks.KUNZITE_BLOCK.get());
        dropSelf(ModBlocks.FRANCIUM_BLOCK.get());
        dropSelf(ModBlocks.RED_DIAMOND_BLOCK.get());
        dropSelf(ModBlocks.RHODIUM_BLOCK.get());
        dropSelf(ModBlocks.MEITNERIUM_BLOCK.get());
        dropSelf(ModBlocks.RED_BERIL_BLOCK.get());
        dropSelf(ModBlocks.ALUMINUM_BLOCK.get());
        dropSelf(ModBlocks.OPAL_BLOCK.get());
        dropSelf(ModBlocks.PYROPE_BLOCK.get());
        dropSelf(ModBlocks.HOWLITE_BLOCK.get());
        dropSelf(ModBlocks.SPINEL_RED_BLOCK.get());
        dropSelf(ModBlocks.HESSONITE_BLOCK.get());
        dropSelf(ModBlocks.AGATE_BLOCK.get());
        dropSelf(ModBlocks.RADIUM_BLOCK.get());
        dropSelf(ModBlocks.LITHIUM_BLOCK.get());
        dropSelf(ModBlocks.PREHNITE_BLOCK.get());
        dropSelf(ModBlocks.IOLITE_RARE_BLOCK.get());
        dropSelf(ModBlocks.OSMIUM_BLOCK.get());
        dropSelf(ModBlocks.AMERICIUM_BLOCK.get());
        dropSelf(ModBlocks.SMOKY_QUARTZ_BLOCK.get());
        dropSelf(ModBlocks.CALCITE_BLOCK.get());
        dropSelf(ModBlocks.MALACHITE_BLOCK.get());
        dropSelf(ModBlocks.CHRYSOPRASE_RARE_BLOCK.get());
        dropSelf(ModBlocks.SAPPHIRE_PINK_BLOCK.get());
        dropSelf(ModBlocks.ANDALUSITE_BLOCK.get());
        dropSelf(ModBlocks.SPINEL_BLOCK.get());
        dropSelf(ModBlocks.GROSSULAR_BLOCK.get());
        dropSelf(ModBlocks.ALEXANDRITE_BLOCK.get());
        dropSelf(ModBlocks.LIVERMORIUM_BLOCK.get());
        dropSelf(ModBlocks.RUTHENIUM_BLOCK.get());
        dropSelf(ModBlocks.TECHNETIUM_BLOCK.get());
        dropSelf(ModBlocks.LEPIDOLITE_BLOCK.get());
        dropSelf(ModBlocks.SPINEL_PURPLE_BLOCK.get());
        dropSelf(ModBlocks.DIOPSIDE_BLOCK.get());
        dropSelf(ModBlocks.POLONIUM_BLOCK.get());
        dropSelf(ModBlocks.PALLADIUM_BLOCK.get());
        dropSelf(ModBlocks.JEREMEJEVITE_BLOCK.get());
        dropSelf(ModBlocks.CHRYSOBERYL_ALMANDINE_BLOCK.get());
        dropSelf(ModBlocks.CHALCEDONY_BLOCK.get());
        dropSelf(ModBlocks.TOPAZ_BLOCK.get());
        dropSelf(ModBlocks.TOURMALINE_PINK_BLOCK.get());
        dropSelf(ModBlocks.COPERNICIUM_BLOCK.get());
        dropSelf(ModBlocks.AMAZONITE_BLOCK.get());
        dropSelf(ModBlocks.RUBY_BLOCK.get());
        dropSelf(ModBlocks.CHAROITE_BLOCK.get());
        dropSelf(ModBlocks.GRANDIDIERITE_BLOCK.get());
        dropSelf(ModBlocks.BOHRIUM_BLOCK.get());
        dropSelf(ModBlocks.RHENIUM_BLOCK.get());
        dropSelf(ModBlocks.SODIUM_BLOCK.get());
        dropSelf(ModBlocks.NIOBIUM_BLOCK.get());
        dropSelf(ModBlocks.DIASPORE_BLOCK.get());
        dropSelf(ModBlocks.SERENDIBITE_BLOCK.get());
        dropSelf(ModBlocks.ZIRCONIUM_BLOCK.get());
        dropSelf(ModBlocks.KYANITE_BLOCK.get());
        dropSelf(ModBlocks.CHRYSOBERYL_CATSEYE_BLOCK.get());
        dropSelf(ModBlocks.AVENTURINE_BLOCK.get());
        dropSelf(ModBlocks.LEAD_BLOCK.get());
        dropSelf(ModBlocks.TAAFFEITE_BLOCK.get());
        dropSelf(ModBlocks.CHRYSOPRASE_BLOCK.get());
        dropSelf(ModBlocks.AMETRINE_BLOCK.get());
        dropSelf(ModBlocks.NICKEL_BLOCK.get());
        dropSelf(ModBlocks.CITRINE_BLOCK.get());
        dropSelf(ModBlocks.SILVER_BLOCK.get());
        dropSelf(ModBlocks.MENDELEVIUM_BLOCK.get());
        dropSelf(ModBlocks.JASPER_BLOCK.get());
        dropSelf(ModBlocks.JADE_NEFRITE_BLOCK.get());
        dropSelf(ModBlocks.OGANESSON_BLOCK.get());
        dropSelf(ModBlocks.TITANIUM_BLOCK.get());
        dropSelf(ModBlocks.CARNELIAN_BLOCK.get());
        dropSelf(ModBlocks.ONYX_BLOCK.get());
        dropSelf(ModBlocks.ROENTGENIUM_BLOCK.get());
        dropSelf(ModBlocks.TANTALUM_BLOCK.get());
        dropSelf(ModBlocks.RHODONITE_BLOCK.get());
        dropSelf(ModBlocks.EINSTEINIUM_BLOCK.get());
        dropSelf(ModBlocks.CALIFORNIUM_BLOCK.get());
        dropSelf(ModBlocks.ALMANDINE_BLOCK.get());
        dropSelf(ModBlocks.TIN_BLOCK.get());
        dropSelf(ModBlocks.ANTIMONY_BLOCK.get());
        dropSelf(ModBlocks.APATITE_BLOCK.get());
        dropSelf(ModBlocks.TENNESSINE_BLOCK.get());
        dropSelf(ModBlocks.KEMPTONITE_BLOCK.get());
        dropSelf(ModBlocks.LABRADORITE_BLOCK.get());
        dropSelf(ModBlocks.NIHONIUM_BLOCK.get());
        dropSelf(ModBlocks.MAGNESIUM_BLOCK.get());
        dropSelf(ModBlocks.SAPPHIRE_BLOCK.get());
        dropSelf(ModBlocks.AQUAMARINE_BLOCK.get());
        dropSelf(ModBlocks.NEPTUNIUM_BLOCK.get());
        dropSelf(ModBlocks.ZOISITE_TANZANITE_BLOCK.get());
        dropSelf(ModBlocks.TORMALINE_RARE_BLOCK.get());
        dropSelf(ModBlocks.TUNSTALLITE_BLOCK.get());
        dropSelf(ModBlocks.BLUE_DIAMOND_BLOCK.get());
        dropSelf(ModBlocks.FLUORITE_BLOCK.get());
        dropSelf(ModBlocks.DANBURITE_BLOCK.get());
        dropSelf(ModBlocks.MUSGRAVITE_BLOCK.get());
        dropSelf(ModBlocks.CHRYSOBERYL_BLOCK.get());
        dropSelf(ModBlocks.HAFNIUM_BLOCK.get());
        dropSelf(ModBlocks.TURQUOISE_BLOCK.get());
        dropSelf(ModBlocks.MOSCOVIUM_BLOCK.get());
        dropSelf(ModBlocks.VANADIUM_BLOCK.get());
        dropSelf(ModBlocks.NOBELIUM_BLOCK.get());
        dropSelf(ModBlocks.TORMALINE_BLOCK.get());
        dropSelf(ModBlocks.APATITE_RARE_BLOCK.get());
        dropSelf(ModBlocks.RUTILE_BLOCK.get());
        dropSelf(ModBlocks.BERKELIUM_BLOCK.get());
        dropSelf(ModBlocks.MOONSTONE_BLOCK.get());
        dropSelf(ModBlocks.PAINITE_BLOCK.get());
        dropSelf(ModBlocks.SODALITE_BLOCK.get());
        dropSelf(ModBlocks.SUNSTONE_BLOCK.get());
        dropSelf(ModBlocks.SPINEL_GREEN_BLOCK.get());
        dropSelf(ModBlocks.JADE_JADEITE_BLOCK.get());
        dropSelf(ModBlocks.SEABORGIUM_BLOCK.get());
        dropSelf(ModBlocks.COBALT_BLOCK.get());
        dropSelf(ModBlocks.TIGERS_EYE_BLOCK.get());
        dropSelf(ModBlocks.CHROMIUM_BLOCK.get());
        dropSelf(ModBlocks.IRIDIUM_BLOCK.get());
        dropSelf(ModBlocks.DUBNIUM_BLOCK.get());
        dropSelf(ModBlocks.BURMESE_RUBY_BLOCK.get());
        dropSelf(ModBlocks.PROTACTINIUM_BLOCK.get());
        dropSelf(ModBlocks.AVENTURINE_FELDSPAR_BLOCK.get());
        dropSelf(ModBlocks.SUGILITE_BLOCK.get());
        dropSelf(ModBlocks.EUCLASE_BLOCK.get());

        dropSelf(ModBlocks.ZOISITE_TANZANITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.HASSIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.PREHNITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.MOLYBDENUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.DARMSTADTIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.RUBY_ORE_BLOCK.get());
        dropSelf(ModBlocks.DIASPORE_ORE_BLOCK.get());
        dropSelf(ModBlocks.COBALT_ORE_BLOCK.get());
        dropSelf(ModBlocks.ANTIMONY_ORE_BLOCK.get());
        dropSelf(ModBlocks.CURIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.AGATE_ORE_BLOCK.get());
        dropSelf(ModBlocks.CHAROITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.AVENTURINE_FELDSPAR_ORE_BLOCK.get());
        dropSelf(ModBlocks.LIVERMORIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.DIOPSIDE_ORE_BLOCK.get());
        dropSelf(ModBlocks.JADE_JADEITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.POUDRETTEITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.SODIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.SEABORGIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.TENNESSINE_ORE_BLOCK.get());
        dropSelf(ModBlocks.HESSONITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.SILVER_ORE_BLOCK.get());
        dropSelf(ModBlocks.POLONIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.RUTILE_ORE_BLOCK.get());
        dropSelf(ModBlocks.CALIFORNIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.IOLITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.SPINEL_GREEN_ORE_BLOCK.get());
        dropSelf(ModBlocks.ANDALUSITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.SPINEL_ORE_BLOCK.get());
        dropSelf(ModBlocks.SUNSTONE_ORE_BLOCK.get());
        dropSelf(ModBlocks.NEPTUNIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.LITHIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.CITRINE_ORE_BLOCK.get());
        dropSelf(ModBlocks.NIOBIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.AMAZONITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.JEREMEJEVITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.LEAD_ORE_BLOCK.get());
        dropSelf(ModBlocks.CHRYSOPRASE_RARE_ORE_BLOCK.get());
        dropSelf(ModBlocks.ZINC_ORE_BLOCK.get());
        dropSelf(ModBlocks.SODALITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.NICKEL_ORE_BLOCK.get());
        dropSelf(ModBlocks.TUNSTALLITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.ALEXANDRITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.PINK_STAR_DIAMOND_ORE_BLOCK.get());
        dropSelf(ModBlocks.FERMIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.PROTACTINIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.SPINEL_RARE_ORE_BLOCK.get());
        dropSelf(ModBlocks.SPINEL_PURPLE_ORE_BLOCK.get());
        dropSelf(ModBlocks.NIHONIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.NOBELIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.PAINITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.CHRYSOBERYL_ORE_BLOCK.get());
        dropSelf(ModBlocks.SAPPHIRE_PINK_ORE_BLOCK.get());
        dropSelf(ModBlocks.LEPIDOLITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.MAGNESIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.TORMALINE_RARE_ORE_BLOCK.get());
        dropSelf(ModBlocks.AVENTURINE_ORE_BLOCK.get());
        dropSelf(ModBlocks.JASPER_ORE_BLOCK.get());
        dropSelf(ModBlocks.RUTHENIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.KYANITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.OGANESSON_ORE_BLOCK.get());
        dropSelf(ModBlocks.CHRYSOPRASE_ORE_BLOCK.get());
        dropSelf(ModBlocks.ROENTGENIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.DANBURITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.RHODIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.IRIDIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.MALACHITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.FRANCIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.TITANIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.PERIDOT_ORE_BLOCK.get());
        dropSelf(ModBlocks.HOWLITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.BOHRIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.RUTHERFORDIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.PALLADIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.BURMESE_RUBY_ORE_BLOCK.get());
        dropSelf(ModBlocks.BLUE_DIAMOND_ORE_BLOCK.get());
        dropSelf(ModBlocks.SUGILITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.JADE_NEFRITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.MEITNERIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.VANADIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.ONYX_ORE_BLOCK.get());
        dropSelf(ModBlocks.EINSTEINIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.KEMPTONITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.GRANDIDIERITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.FLEROVIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.COPERNICIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.AMETRINE_ORE_BLOCK.get());
        dropSelf(ModBlocks.HAFNIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.ALUMINUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.BENITOITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.RHODONITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.EUCLASE_ORE_BLOCK.get());
        dropSelf(ModBlocks.TANTALUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.TIGERS_EYE_ORE_BLOCK.get());
        dropSelf(ModBlocks.RHENIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.PLATINUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.MENDELEVIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.SPINEL_RED_ORE_BLOCK.get());
        dropSelf(ModBlocks.TAAFFEITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.BISMUTH_ORE_BLOCK.get());
        dropSelf(ModBlocks.TURQUOISE_ORE_BLOCK.get());
        dropSelf(ModBlocks.MOSCOVIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.APATITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.IOLITE_RARE_ORE_BLOCK.get());
        dropSelf(ModBlocks.CHROMIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.CHALCEDONY_ORE_BLOCK.get());
        dropSelf(ModBlocks.BERKELIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.KUNZITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.LABRADORITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.AMERICIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.RHODOLITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.ZIRCON_ORE_BLOCK.get());
        dropSelf(ModBlocks.TOURMALINE_PINK_ORE_BLOCK.get());
        dropSelf(ModBlocks.CHRYSOBERYL_CATSEYE_ORE_BLOCK.get());
        dropSelf(ModBlocks.MANGANESE_ORE_BLOCK.get());
        dropSelf(ModBlocks.ZIRCONIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.GROSSULAR_ORE_BLOCK.get());
        dropSelf(ModBlocks.TECHNETIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.CHRYSOBERYL_ALMANDINE_ORE_BLOCK.get());
        dropSelf(ModBlocks.SPHENE_ORE_BLOCK.get());
        dropSelf(ModBlocks.APATITE_RARE_ORE_BLOCK.get());
        dropSelf(ModBlocks.MOONSTONE_ORE_BLOCK.get());
        dropSelf(ModBlocks.SMOKY_QUARTZ_ORE_BLOCK.get());
        dropSelf(ModBlocks.FLUORITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.TOPAZ_ORE_BLOCK.get());
        dropSelf(ModBlocks.SAPPHIRE_ORE_BLOCK.get());
        dropSelf(ModBlocks.CARNELIAN_ORE_BLOCK.get());
        dropSelf(ModBlocks.SERENDIBITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.LAWRENCIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.AQUAMARINE_ORE_BLOCK.get());
        dropSelf(ModBlocks.CALCITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.PYROPE_ORE_BLOCK.get());
        dropSelf(ModBlocks.OPAL_ORE_BLOCK.get());
        dropSelf(ModBlocks.DUBNIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.RED_DIAMOND_ORE_BLOCK.get());
        dropSelf(ModBlocks.RED_BERIL_ORE_BLOCK.get());
        dropSelf(ModBlocks.ALMANDINE_ORE_BLOCK.get());
        dropSelf(ModBlocks.TORMALINE_ORE_BLOCK.get());
        dropSelf(ModBlocks.MUSGRAVITE_ORE_BLOCK.get());
        dropSelf(ModBlocks.TIN_ORE_BLOCK.get());
        dropSelf(ModBlocks.OSMIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.RADIUM_ORE_BLOCK.get());
        dropSelf(ModBlocks.SPINEL_BLUE_ORE_BLOCK.get());
    }

    protected LootTable.Builder createMultipleOreDrops(Block pBlock, Item item, float minDrops, float maxDrops) {
        HolderLookup.RegistryLookup<Enchantment> registrylookup = this.registries.lookupOrThrow(Registries.ENCHANTMENT);
        return this.createSilkTouchDispatchTable(pBlock,
                this.applyExplosionDecay(pBlock, LootItem.lootTableItem(item)
                        .apply(SetItemCountFunction.setCount(UniformGenerator.between(minDrops, maxDrops)))
                        .apply(ApplyBonusCount.addOreBonusCount(registrylookup.getOrThrow(Enchantments.FORTUNE)))));
    }

    @Override
    protected Iterable<Block> getKnownBlocks() {
        return ModBlocks.BLOCKS.getEntries().stream().map(Holder::value)::iterator;
    }
}